backend:
  name: github
  repo: bramkerckhoffs/docs
  branch: main
  base_url: https://api.netlify.com
  site_domain: lustrous-puffpuff-9ca837.netlify.app

media_folder: static/images
public_folder: /docs/images

collections:

  - name: terraform
    label: Terraform
    folder: content/terraform
    create: true
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Intro, name: intro, widget: string, required: false }
      - { label: Datum, name: date, widget: datetime, format: "YYYY-MM-DD", time_format: false }
      - { label: Volgorde, name: weight, widget: number, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Inhoud, name: body, widget: markdown }

  - name: azure
    label: Azure
    folder: content/azure
    create: true
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Intro, name: intro, widget: string, required: false }
      - { label: Datum, name: date, widget: datetime, format: "YYYY-MM-DD", time_format: false }
      - { label: Volgorde, name: weight, widget: number, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Inhoud, name: body, widget: markdown }

  - name: stijlgids
    label: Stijlgids
    folder: content/stijlgids
    create: true
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Intro, name: intro, widget: string, required: false }
      - { label: Datum, name: date, widget: datetime, format: "YYYY-MM-DD", time_format: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Inhoud, name: body, widget: markdown }
